# Generated by Django 4.2.8 on 2023-12-23 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=25, null=True)),
                ('disability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('previous_experience', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('previous_training', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('physicians_name', models.CharField(max_length=75)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
