# Generated by Django 4.2.8 on 2024-01-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contactmerequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMeRequest',
            new_name='ContactRequest',
        ),
    ]
