# Generated by Django 4.2.8 on 2024-01-02 21:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_contactmerequest_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='pt_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
